### ISSUE TITLE
Be less strict in the stack trace buffer

### ISSUE THREAD

**Issue by m0smith** [m0smith/malabar-mode#147]
In specfic support:
```
at org.ihc.mh.portalmessaging.service.impl.MessageRouting.computeMessageDestination(MessageRouting.java:187) ~[mh-portalmessaging-service-14.1.4-20141118.175847-4.jar:na]
at org.ihc.mh.portalmessaging.service.impl.MessageRouting.messageDestination(MessageRouting.java:275) ~[mh-portalmessaging-service-14.1.4-20141118.175847-4.jar:na]
at org.ihc.mh.portalmessaging.service.impl.PortalMessagingServiceImpl.routeMessage(PortalMessagingServiceImpl.java:568) ~[mh-portalmessaging-service-14.1.4-20141118.175847-4.jar:na]
at org.ihc.mh.portalmessaging.service.impl.PortalMessagingServiceImpl.sendMessage(PortalMessagingServiceImpl.java:376) ~[mh-portalmessaging-service-14.1.4-20141118.175847-4.jar:na]
at org.ihc.mh.portalmessaging.service.impl.PortalMessagingServiceImpl.sendNewMessage(PortalMessagingServiceImpl.java:329) ~[mh-portalmessaging-service-14.1.4-20141118.175847-4.jar:na]
at org.ihc.phr.mc.portlet.sendmessage.AskAQuestionController.sendMessage(AskAQuestionController.java:227) 
```

**Comment by m0smith** [comment]
fixed
